# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHash',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='messageHandler.Message')),
                ('hash', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
