# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehash',
            name='hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messagehash',
            name='message',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
